CREATE DATABASE IF NOT EXISTS NAIVE;
USE NAIVE;

CREATE TABLE IF NOT EXISTS Networks (
	NetworkID INT AUTO_INCREMENT PRIMARY KEY,
	NetworkName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Subnets (
	SubnetID INT AUTO_INCREMENT PRIMARY KEY,
	NetworkID INT,
	SubnetAddress VARCHAR(18) NOT NULL,
	Description VARCHAR(255),
	FOREIGN KEY (NetworkID) REFERENCES Networks(NetworkID)
);

CREATE TABLE IF NOT EXISTS Assets (
	SubnetID INT,
	IPV4 VARCHAR(15) PRIMARY KEY,
	DNS VARCHAR(50),
	Date_last_seen VARCHAR(50),
	FOREIGN KEY (SubnetID) REFERENCES Subnets(SubnetID)
);

CREATE TABLE IF NOT EXISTS  MACInfo (
	-- MACBindID INT AUTO_INCREMENT PRIMARY KEY,
	IPV4 VARCHAR(15) NOT NULL,
	MAC_Address VARCHAR(17) NOT NULL,
	Vendor VARCHAR(50),
	Date_last_seen DATE DEFAULT CURRENT_DATE,
	PRIMARY KEY (MAC_Address, IPV4, Date_last_seen),
	FOREIGN KEY (IPV4) REFERENCES Assets(IPV4) 
);